"""empty message

Revision ID: 5c54a42d82fe
Revises: c01ee82fc9c7
Create Date: 2023-01-14 16:15:13.089027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c54a42d82fe'
down_revision = 'c01ee82fc9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=150), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], name=op.f('fk_keywords_board_id_board'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'keyword', name=op.f('pk_keywords'))
    )
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('keyword_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_board_title'), ['title'])
        batch_op.create_foreign_key(batch_op.f('fk_board_keyword_id_keywords'), 'keywords', ['keyword_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.alter_column('study_score',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('study_score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('age')

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_board_keyword_id_keywords'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_board_title'), type_='unique')
        batch_op.drop_column('keyword_id')
        batch_op.drop_column('views')

    op.drop_table('keywords')
    # ### end Alembic commands ###
